VERSION 5.00
Object = "{3B7C8863-D78F-101B-B9B5-04021C009402}#1.1#0"; "RICHTX32.OCX"
Begin VB.Form RichTextBox_FRM 
   Caption         =   "Form1"
   ClientHeight    =   3195
   ClientLeft      =   60
   ClientTop       =   345
   ClientWidth     =   4680
   LinkTopic       =   "Form1"
   ScaleHeight     =   3195
   ScaleWidth      =   4680
   StartUpPosition =   3  'Windows Default
   Begin RichTextLib.RichTextBox RichTextBox1 
      Height          =   855
      Left            =   0
      TabIndex        =   0
      Top             =   0
      Width           =   960
      _ExtentX        =   1693
      _ExtentY        =   1508
      _Version        =   327680
      TextRTF         =   $"RichTextBox_FRM.frx":0000
   End
End
Attribute VB_Name = "RichTextBox_FRM"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
