VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "eDatosAuxiliaresCampos"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
    
Public MarcaBorrado As Integer
Public Encabezado As String
Public Formula As String
Public CampoEditable As String
Public ColumnaCampoEco As String
Public Total As String
Public DejarLibre As String
Public Formato As String
