VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "eRecepcion"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public NumeroProveedor As Long
Public CodigoEmpresa As Integer
Public FechaRecepcion As Integer
Public RemitoProveedor As String
Public FacturaProveedor As String
Public PatenteTransporte As String
Public Deposito As Integer
Public UbicacionFisica As String
Public NumConvig As String
Public Status As Integer

