CREATE TABLE [dbo].[REPUESRE](
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [CodigoReparacion] [nvarchar](16) NOT NULL,
    [CodigoInterno] [smallint] NOT NULL,
    [Uso] [real] NOT NULL,
    [Status] [smallint] NULL,
    [AddRecord] [datetime2](7) NULL,
    [LastUpdate] [datetime2](7) NULL,
    [CodiEmprNet] [int] NULL,
    [NumUsuar] [int] NULL,
 CONSTRAINT [PK_REPUESRE] PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_REPUESRE_CodigoReparacion_CodigoInterno] ON [dbo].[REPUESRE]
(
    [CodigoReparacion] ASC,
    [CodigoInterno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
