CREATE TABLE [dbo].[INDIREP](
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [Codigo] [nvarchar](24) NOT NULL,
    [Descripcion] [nvarchar](128) NOT NULL,
    [Status] [smallint] NULL,
    [AddRecord] [datetime2](7) NULL,
    [LastUpdate] [datetime2](7) NULL,
    [CodiEmprNet] [int] NULL,
    [NumUsuar] [int] NULL,
 CONSTRAINT [PK_INDIREP] PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_INDIREP_Codigo] ON [dbo].[INDIREP]
(
    [Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
